- hosts: localhost
  pre_tasks:
    - set_fact:
        homedir: "{{ lookup('env', 'HOME') }}"
        target_username: "{{ lookup('env', 'USER') }}"
        home_script: "{{ home_script | default('.scripts') }}"
        is_admin: "{{ is_admin | default('false') }}"
  vars_files:
    - vars/{{ target_username|default('default') }}.yml
  roles:
    - home

