- name: Clone repository
  git:
    repo: https://github.com/josuebrunel/myscripts.git
    dest: "{{ homedir }}/{{ home_script }}/"

- name: Get Python 2 user site
  command: "python{{ item }} -m site --user-site"
  register: python_user_sites
  with_items:
    - 2
    - 3


- name: Create python user site
  file:
    path: "{{ item.stdout }}"
    state: directory
    mode: '0755'
  with_items: "{{ python_user_sites.results }}"


- name: Add myutils.pth to python user site
  file:
    src: "{{homedir}}/{{ home_script }}/python/myutils.pth"
    dest: "{{ item.stdout }}/myutils.pth"
    state: link
  with_items: "{{ python_user_sites.results }}"


- name: Add myutils package to python user site
  file:
    src: "{{ homedir }}/{{ home_script }}/python/myutils/"
    dest: "{{ item.stdout }}/myutils"
    state: link
    force: yes
  with_items: "{{ python_user_sites.results }}"


- name: Create user local bin directory
  file:
    path: "{{ homedir }}/.local/bin/"
    state: directory
    mode: '0755'

- name: Copy pymanager to local bin
  file:
    src: "{{ homedir }}/{{ home_script }}/bin/pymanager.py"
    path: "{{ homedir }}/.local/bin/pymanager"
    state: link


- name: Copy home config file
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ homedir }}/.{{item}}"
    state: link
    force: yes
  with_items:
    - gitignore
    - irbrc
    - pdbrc
    - sqliterc


- name: Copy home config file with vars
  template:
      src: "{{ role_path }}/templates/{{ item }}"
      dest: "{{ homedir }}/.{{item}}"
  with_items:
      - gitconfig
      - profile
      - pypirc

- name: Create sudoers file if admin
  copy:
    content: "{{ target_username }}  ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ target_username }}"
  when: is_admin
  become: yes
