- name: Install qbittorrent-nox
  apt:
      name: "{{ packages }}"
      state: present
  vars:
      packages:
        - qbittorrent
        - qbittorrent-nox

- name: Ensure group media exists
  group:
      name: media
      state: present

- name: Add user media
  user:
      name: media
      group: media
      shell: /bin/bash
      home: /home/media/
      move_home: yes
      state: present

- name: Set up qbittorrent-nox service
  copy:
      src: "{{ role_path }}/files/qbittorrent.service"
      dest: /etc/systemd/system/qbittorrent.service
      mode: 0777
  notify: Starts qbittorrent service
  tags:
    - qbittorrent
